# Generated by Django 3.0.3 on 2020-02-13 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Buyers')),
            ],
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SellerUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Privileges')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sellers')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('costsite', models.CharField(max_length=50)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Buyers')),
            ],
        ),
        migrations.CreateModel(
            name='Cheques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('buid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BuyerUsers')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Departments')),
                ('suid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SellerUsers')),
            ],
        ),
        migrations.AddField(
            model_name='buyerusers',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Privileges'),
        ),
    ]
