# Generated by Django 3.0.3 on 2020-03-26 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200312_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Pending'), (2, 'Done')], default=0, verbose_name='Status')),
                ('description', models.CharField(max_length=200, verbose_name='Placeholder for cheque information fields')),
                ('price', models.FloatField(verbose_name='Price')),
                ('created', models.DateTimeField(editable=False, verbose_name='Cheque created')),
                ('modified', models.DateTimeField(verbose_name='Last modified')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_department', to='api.Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
