# Generated by Django 3.0.3 on 2020-04-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200330_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheque_organization', to='api.Organization'),
        ),
    ]
