# Generated by Django 3.0.3 on 2020-04-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200401_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='superuser',
            field=models.BooleanField(default=True, verbose_name='Super User'),
            preserve_default=False,
        ),
    ]
