# Generated by Django 3.0.3 on 2020-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='superuser',
            field=models.BooleanField(default=False, verbose_name='Super User'),
        ),
    ]
