# Generated by Django 3.0.3 on 2020-04-18 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200418_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(null=True, related_name='department_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
