# Generated by Django 3.0.3 on 2020-04-18 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200418_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(related_name='department_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
