# Generated by Django 3.0.3 on 2020-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200418_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='superuser',
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.BooleanField(default=False, verbose_name='Department manager'),
        ),
    ]
