# Generated by Django 3.0.3 on 2020-05-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_cheque_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='manager',
            new_name='is_manager',
        ),
    ]
