# Generated by Django 3.0.3 on 2020-05-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200514_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
    ]
