version: '3'
services:
    backend: 
        image: emiln17/edico-be:dev
        ports: 
            - '8000:8000'
    frontend:
        image: emiln17/edico-fe:dev
        ports: 
            - '3000:3000'
        depends_on: 
            - backend

