# Generated by Django 3.0.3 on 2020-02-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buyers',
            table='buyers',
        ),
        migrations.AlterModelTable(
            name='buyerusers',
            table='buyer_users',
        ),
        migrations.AlterModelTable(
            name='cheques',
            table='cheques',
        ),
        migrations.AlterModelTable(
            name='departments',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='privileges',
            table='privileges',
        ),
        migrations.AlterModelTable(
            name='sellers',
            table='sellers',
        ),
        migrations.AlterModelTable(
            name='sellerusers',
            table='seller_users',
        ),
    ]
