import { StyleSheet } from 'react-native';
import {
  appPrimaryColor, appTextColor, appFont, appSecondaryColor,
} from '../../styles/style-config';

export default StyleSheet.create({
  container: {
    flex: 1,
    textAlign: 'center',
    backgroundColor: appPrimaryColor,
    justifyContent: 'flex-start',
  },
  content: {
    alignItems: 'center',
    marginRight: 'auto',
    marginLeft: 'auto',
    justifyContent: 'center',
    width: '80%',
    color: appTextColor,
    height: '80%',
  },
  userItem: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomColor: appSecondaryColor,
    borderBottomWidth: 1,
  },
  itemUser: {
    padding: 10,
    fontFamily: appFont,
    flex: 1,
    fontSize: 23,
    backgroundColor: appPrimaryColor,
    textAlign: 'right',
  },
  userIcon: {
    fontSize: 200,
  },
  userDepartmentDesc: {
    width: '100%',
    textAlign: 'center',
    fontFamily: appFont,
    marginTop: '15%',
    fontSize: 23,
  },
  centerItem: {
    padding: 10,
    width: '100%',
    textAlign: 'center',
    fontFamily: appFont,
    fontSize: 23,
  },
  itemDesc: {
    flex: 0,
    padding: 10,
    fontFamily: appFont,
    fontSize: 23,
  },
  changePW: {
    marginTop: 'auto',
    backgroundColor: appSecondaryColor,
    borderWidth: 2,
    borderRadius: 15,
    paddingRight: 15,
    paddingLeft: 15,
  },
  defaultPick: {
    flex: 0,
    flexDirection: 'row',
    paddingRight: 10,
    paddingLeft: 10,
    justifyContent: 'flex-start',
    alignItems: 'center',
    minWidth: '100%',
    minHeight: 30,
    borderBottomWidth: 1,
    borderBottomColor: appSecondaryColor,
  },
  oneCostsite: {
    flex: 0,
    flexDirection: 'row',
    margin: 15,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: '100%',
    minHeight: 30,
    borderBottomWidth: 1,
    borderBottomColor: appSecondaryColor,
  },
  listItem: {
    flex: 0,
    flexDirection: 'row',
    marginBottom: 10,
    paddingLeft: 20,
    paddingRight: 20,
    alignItems: 'center',
    minWidth: '80%',
    minHeight: 50,
    borderBottomWidth: 1,
    borderBottomColor: appSecondaryColor,
  },
  rightMark: {
    fontSize: 30,
    marginLeft: 'auto',
    fontFamily: appFont,
  },
  costsiteText: {
    fontSize: 30,
    fontFamily: appFont,
  },
});
