# Generated by Django 3.0.3 on 2020-02-24 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20200220_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('costsite', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('buyer_seller', models.BooleanField()),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super', models.BooleanField()),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.RemoveField(
            model_name='departments',
            name='bid',
        ),
        migrations.DeleteModel(
            name='Privileges',
        ),
        migrations.DeleteModel(
            name='Sellers',
        ),
        migrations.RemoveField(
            model_name='cheques',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='cheques',
            name='did',
        ),
        migrations.RemoveField(
            model_name='cheques',
            name='suid',
        ),
        migrations.AddField(
            model_name='cheques',
            name='status',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheques',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cheque_user_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Buyers',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.AddField(
            model_name='department',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheques',
            name='dep_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cheque_dep_id', to='api.Department'),
            preserve_default=False,
        ),
    ]
